name: acr-2
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
permissions:
  id-token: write
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: https://ociconformancetest.azurecr.io
          OCI_NAMESPACE: ocitest/push
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          OCI_TEST_PUSH: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
