name: acr-all
on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
permissions:
  id-token: write
  contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: https://shizheus.azurecr.io
          OCI_NAMESPACE: ocitest/alltests
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          OCI_TEST_PULL: 1
          OCI_TEST_PUSH: 1
          OCI_TEST_CONTENT_DISCOVERY: 1
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
          OCI_CROSSMOUNT_NAMESPACE: ocitest/mount-source
          OCI_DEBUG: 0
