name: acr-4
on:
  repository_dispatch:
    types:
      - manual-trigger
      - manual-trigger-acr
      - manual-trigger-acr-4
  schedule:
    - cron: '0 6 * * *'
permissions:
      id-token: write
      contents: read
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Run OCI Distribution Spec conformance tests
        uses: opencontainers/distribution-spec@main
        env:
          OCI_ROOT_URL: https://ociconformancetest.azurecr.io
          OCI_NAMESPACE: ocitest/content-management
          OCI_USERNAME: ${{ secrets.ACR_USERNAME }}
          OCI_PASSWORD: ${{ secrets.ACR_PASSWORD }}
          OCI_TEST_CONTENT_MANAGEMENT: 1
          OCI_HIDE_SKIPPED_WORKFLOWS: 1
